import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";
export const metadata: Metadata = { title: "Privacy Policy · CodeForge" };
export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" intro="This notice explains how CodeForge handles information when you create an account, build APIs, or contact us." sections={[
    { title: "Information we handle", body: "Account information includes your name, email address, password hash and configured security credentials. We also process project names, submitted prompts, generated files, requirements, architecture, review findings, tests and runtime output. Contact messages include your account name, email, optional phone number and message. Device, session and security records may include IP addresses, browser information and timestamps." },
    { title: "Why we use it", body: "We use this information to provide accounts and API generation, verify email addresses, operate security features, deliver requested messages, investigate failures and prevent abuse. Project and run information lets you inspect results and continue your work." },
    { title: "AI providers and other services", body: "Generating an API requires sending your prompt and relevant run context, which can include code and prior agent output, to external AI providers. Fallback providers may receive the same context when a request fails. Hosting, database, email and operational monitoring services may also process information needed to operate CodeForge. Their handling depends on the providers and configuration used for the service. Do not submit passwords, API keys, confidential information or personal data you are not authorized to share. We do not promise that external providers never retain inputs or use them for training." },
    { title: "Cookies and browser storage", body: "CodeForge uses a session cookie to authenticate browser requests and a session-presence cookie to display account state. Browser storage also holds a device identifier for device and session security. These are functional service features; they are not a substitute for server-side authorization. Clearing cookies can sign you out, and clearing device storage can change how your browser is recognized." },
    { title: "Retention and deletion", body: "Project and run information is retained to support your history and downloadable results. Account deletion is available in account settings and removes associated application records and artifacts through the deletion workflow. Contact emails, operational logs, backups and copies held by external providers can follow separate retention processes. CodeForge does not currently publish a fixed retention period for every category or guarantee immediate removal from every backup or provider system. Contact us for a deletion request or clarification." },
    { title: "Your choices and requests", body: "You can manage supported account and security settings, delete projects and request account deletion. You may contact us to request access, correction or deletion of your personal information, or raise a privacy concern. We may need to verify your identity. Requests are handled subject to applicable law and the information we actually hold." },
    { title: "Security and updates", body: "CodeForge uses account authentication and owner-scoped access controls. No service can guarantee absolute security. If you suspect account misuse, review your security settings and contact us. We may update this notice when the service changes; the date above identifies the latest version." },
  ]} />;
}
