import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";
export const metadata: Metadata = { title: "Terms of Use · CodeForge" };
export default function TermsPage() {
  return <LegalPage title="Terms of Use" intro="These terms describe the conditions for using CodeForge’s accounts, AI-assisted API generation and related features." sections={[
    { title: "Using CodeForge", body: "By creating an account or using CodeForge, you agree to these terms. Use the service only when you are legally able to accept them. CodeForge is an evolving service for generating and inspecting API projects; features, availability and supported limits may change." },
    { title: "Your account", body: "Provide accurate account information and protect your credentials, passkeys and recovery codes. You are responsible for activity you authorize through your account. Notify us if you suspect unauthorized access. Do not share credentials or impersonate another person." },
    { title: "Acceptable use", body: "Do not use CodeForge for unlawful activity, malware, unauthorized access, harassment or infringement of others’ rights. Do not upload secrets or information you lack permission to disclose, bypass safeguards, or deliberately overload the service. We may restrict access to address abuse, security risks or legal requirements." },
    { title: "Inputs and generated results", body: "You retain any rights you already hold in your submitted material. You authorize the processing and sharing of that material needed to provide the requested features, as described in the Privacy Policy. CodeForge does not claim ownership of your inputs or generated results. AI output may resemble other output and may include material subject to third-party rights or licenses; we do not guarantee exclusivity or that every result is free of restrictions." },
    { title: "Review before deployment", body: "Generated code can contain errors, security weaknesses or incomplete behavior. Passing generated tests does not establish production readiness. You are responsible for reviewing code, dependencies, licenses, security and data handling before using or deploying an API. Do not treat generated results as professional advice or a guarantee of correctness." },
    { title: "Availability and limits", body: "AI provider limits, outages and bounded repair loops can interrupt or stop runs. CodeForge does not guarantee a successful build, uninterrupted service or permanent availability of every feature. Keep your own copies of important results. Any future paid offering will need its pricing and payment terms disclosed separately." },
    { title: "Responsibility and account closure", body: "The service is provided as available, without a promise that it will meet every requirement or be error-free. Nothing in these terms removes rights or responsibilities that applicable law does not allow to be excluded. You can request account deletion through settings. We may suspend or close access where needed to address violations, security or legal obligations." },
    { title: "Changes to these terms", body: "We may revise these terms as CodeForge changes. Updated terms will carry a new date. Material changes should be communicated before they apply where required by law. Contact us if you have questions about a change or your use of the service." },
  ]} />;
}
